global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'telegram'
receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token:  6351822082:AAGf7owyEk1zvAGPoOprfSN4--1MdP4Cwn4
    api_url:  https://api.telegram.org
    chat_id:  -847528473
    parse_mode: '' 
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
